defaults:
    target:
        host: www.somehost.com
        scheme: https://

Sections:
    website:
        rules:
            - HttpHeaderXSSProtectionSecure
            - HttpHeaderExposeLanguage
            - HttpHeaderContentTypeNoSniffing
            - HttpHeaderCookieWithHttpOnlyFlag
            - HttpHeaderHSTSPresent
            - HttpHeaderHSTSWithSubdomains
            - HttpHeaderCookieWithHttpSecureFlag


