language: php
php:
- 7.0
- 5.6
- 5.5
before_install:
- travis_retry composer self-update
- phpenv config-rm xdebug.ini
install:
- travis_retry composer install --no-interaction
script: phpunit
before_deploy:
- composer update --no-dev
- composer dump-autoload -a
- echo "phar.readonly = Off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- curl -LSs https://box-project.github.io/box2/installer.php | php
- php box.phar build
deploy:
  provider: releases
  api_key:
    secure: DNbGfb/Bl5Waz/K2LEMcWLAbm6iBA5K+3sQTqnsKpyKqcadNjmuCo/gkqFqVu60J6EQASEsUrhVDoCICuYzM/0saeei1nBku053ILEaWfwNjx8xdQyfKG7UZpKcjoZs1QqjLEFnw5Ivu3uWThH4HAWjg45TjQrPiVloN6M50reT1tv6naDyfk31k9O/1VrVxUd95ml0QBeo2gC19SS+3Xpy6fOPyn3AbX+r9PqBILjhzU3wVNrMto+Uw5e774PIdPizntkLON/EnVgshntOUNfD6jV1Mnqz3Z16ZBNneiFRoz5JDGTKYw91XTRMcd3WWwpqaqRThEdEyHKmVIuVUvrjJf+XdqIwAyEnN93oHVUW0a+3iDv2+5yZp/1rFz4l2veIh4dqHb0UD1gYNxY9Rz5dfKQAm8PR6hiJGwqcd2lroUNisLHB5+l5aYu6tFXoup7lfKlDI0TY5Uhzec4qmvEm8n44ATYSy6SarQrcUJ9p4MTdwYfI/ll+4OfratoP+4gGOEqcGD4w7m40H2C77m2IsEDeAqWe9LiB6gZu4apu7m8B8QXWZvENnqbROcJxxT94+zz95Sh+AOTWW/8ArWkkDW/Am54yhmB2Sc1/68IBgn3AfahTwwJGHQyw3CODb+P5Owo8yt9drsSbjsrgu4FVotzmX3OR4dDMIa0ufJAk=
  file: 'kickoff.phar'
  skip_cleanup: true
  on:
    tags: true
    php: 5.5

