Rule definitions:
    HttpHeaderXSSProtectionPresent:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HTTP Header: X-XSS-Protection present"]]
            - ["setHeaderToSearchFor", ["X-XSS-Protection"]]

    HttpHeaderXSSProtectionSecure:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HTTP Header: X-XSS-Protection present and has value 1;mode block"]]
            - ["setHeaderToSearchFor", ["X-XSS-Protection"]]
            - ["setValue", ["1; mode=block"]]

    HttpHeaderExposeLanguage:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderNotPresent
        calls:
            - ["setName", ["HTTP Header: Exposes language not present"]]
            - ["setHeaderToSearchFor", ["X-Powered-By"]]

    HttpRequestTime:
        class: \Frickelbruder\KickOff\Rules\HttpRequestTime

    HttpHeaderHasFarFutureExpiresHeader:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasFarFutureExpiresHeader

    HttpHeaderHasEtag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName",  ["HTTP Header: Has Etag"]]
            - ["setHeaderToSearchFor", ["ETag"]]

    HttpHeaderResourceFound:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["200"]]

    HttpHeaderResourceMovedPermanently:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderResourceMovedPermanently
        calls:
            - ["setValue", ["301"]]

    HttpHeaderNotModifiedOnIfModifiedSince:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderRespondsToIfModifiedSince

    HttpHeaderResourceIsMissing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["404"]]

    HttpHeaderResourceIsGzipped:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderResourceIsGzipped

    HttpHeaderContentTypeNoSniffing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HTTP Header: X-Content-Type-Options:nosniff present"]]
            - ["setHeaderToSearchFor", ["X-Content-Type-Options"]]
            - ["setValue", ["nosniff"]]

    HttpHeaderFrameOptionsSameOrigin:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HTTP Header: X-Frame-Options:SAMEORIGIN present"]]
            - ["setHeaderToSearchFor", ["X-Frame-Options"]]
            - ["setValue", ["SAMEORIGIN"]]

    HttpHeaderCookieWithHttpOnlyFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HTTP Header: Cookie has HttpOnly-flag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; HttpOnly"]]

    HttpHeaderCookieWithHttpSecureFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HTTP Header: Cookie has Secure-flag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; Secure"]]

    #Better use HttpHeaderHSTSWithSubdomains
    HttpHeaderHSTSPresent:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HTTP Header: Strict-Transport-Security si present"]]
            - ["setHeaderToSearchFor", ["Strict-Transport-Security"]]

    HttpHeaderHSTSWithSubdomains:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HTTP Header: Strict-Transport-Security has includeSubDomains-Flag"]]
            - ["setHeaderToSearchFor", ["Strict-Transport-Security"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; includeSubDomains"]]

    TitleTagLength:
        class: \Frickelbruder\KickOff\Rules\TitleTagLength

    MetaDescriptionLength:
        class: \Frickelbruder\KickOff\Rules\MetaDescriptionLength

    OGPropertyPresent:
        class: \Frickelbruder\KickOff\Rules\OgPropertyPresent

    TwitterProperty:
        class: \Frickelbruder\KickOff\Rules\TwitterProperty

    LinkRelCanonical:
        class: \Frickelbruder\KickOff\Rules\LinkRelCanonical

    LinkHrefLang:
        class: \Frickelbruder\KickOff\Rules\LinkHrefLang

    AppleTouchIcon:
        class: \Frickelbruder\KickOff\Rules\AppleTouchIcon

    MetaGeneratorNotPresent:
        class: \Frickelbruder\KickOff\Rules\MetaGeneratorNotPresent

    FindStringOnWebsite:
        class: \Frickelbruder\KickOff\Rules\FindStringOnWebsite

    H1TagPresent:
        class: \Frickelbruder\KickOff\Rules\H1TagPresent

    ExactlyOneH1TagPresent:
        class: \Frickelbruder\KickOff\Rules\H1TagPresent
        calls:
            - ["setName", ["Exactly 1 H1-rag present"]]
            - ["allowMultipleTags", [false]]

    ValidSslCertificate:
        class: \Frickelbruder\KickOff\Rules\ValidSslCertificate
